defaults:
  model: cnn
  data: dummy

callbacks:
  checkpoint:
    save_every_steps: 1000
    keep_every_epochs: 10

  logging: true
  plot:
    plot_every_epochs: 5
    metrics_to_plot: ["loss"]
    output_path: "runs/exp1"

# factory_name:

epochs: 3
output_dir: runs/
